from tkinter import *
import sqlite3
top=Tk()
top.geometry()
conn=sqlite3.connect('ecommerce1.db')
print("open database successfully")
c=conn.cursor()
c.execute("""CREATE TABLE IF NOT EXISTS
ECOMMERCE(NAME TEXT,Amount TEXT)""")
print("TABLE CREATED successfully")
conn.commit()
conn.close()
def insert():
    s1=e1.get()
    s2=e2.get()
    print(s1,s2)
    conn=sqlite3.connect('ecommerce.db')
    print('open db')
    c=conn.cursor()
    sql= '''INSERT INTO ECOMMERCE
    (NAME,AMOUNT) VALUES (?,?)'''
    val=(s1,s2)
    c.execute(sql,val)
    conn.commit()
    l_add=Label(top,text="record inserted successfully")
    l_add.place(x=100,y=270)
    print("record inserted successfully with values",(s1,s2))
    conn.close()
def view():
    conn=sqlite3.connect('ecommerce.db')
    c=conn.cursor()
    c.execute("""SELECT * FROM ECOMMERCE""")
    s=c.fetchall()
    s1=str(s)
    print("records in db are", s)
    l_view=Label(top,text=("records in db are"))
    l_view.place(x=10,y=290)
    T=Text(top,height=10,width=80)
    T.place(x=140,y=310)
    T.insert(INSERT,s1)
    conn.commit()
    conn.close()
def delete():
    conn=sqlite3.connect('ecommerce.db')
    c=conn.cursor()
    n1=e1.get()
    print(n1)
    sql='DELETE FROM ECOMMERCE WHERE NAME=?'
    c.execute(sql,(n1,))
    l_del=Label(top,text='record deleted')
    l_del.place(x=330,y=140)
    conn.commit()
    conn.close()
l_main=Label(top,text="E-commerce application using TKINTER",
font=("Helvetica",22),fg="blue",bg="lavender")
l_main.place(x=20,y=20)
l1=Label(top,text="Product Name",font="Helvetica 9 bold")
l1.place(x=60,y=80)
e1= Entry(top)
e1.place(x=160,y=80)
l2=Label(top,text="Amount",font="Helvetica 9 bold")
l2.place(x=60,y=110)
e2= Entry(top)
e2.place(x=160,y=110)
B1= Button(top, text="Insert",font="Helvetica 9 bold",command=insert)
B1.place(x=100,y=200)
B2= Button(top, text="view",font="Helvetica 9 bold",command=view)
B2.place(x=180,y=200)
B3= Button(top, text="delete",font="Helvetica 9 bold",command=delete)
B3.place(x=240,y=200)
top.mainloop()